### ISSUE TITLE
Unable to use custom font

### ISSUE THREAD

**Issue by erwagasore** [username0x0a/Tamperish#7]
I want to change the font of `news.ycombinator` from `sans-serif` to `monospaced` custom font called `PragmataPro` which I have on my computer.

This is failing I also tried to use `google font` using `@import` in CSS but this is not working as well.

**Comment by username0x0a** [comment]
```
body * {
	font-family: monospace !important;
}
```

👍

**Comment by erwagasore** [comment]
@username0x0a

This work by picking a generic monospaced font family.
```css
body * {
	font-family: monospace !important;
}
```

But this doesn't work when pointing to a locally available font e.g. `PragmataPro`
```css
body * {
	font-family: PragmataPro !important;
}
```
